<?xml version="1.0" encoding="utf-8"?><Database Name="ToDoDb" Class="ToDoSqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MEETGOTI\SQLEXPRESS;Initial Catalog=ToDoDb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ToDoDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bargraph" Member="Bargraphs">
    <Type Name="Bargraph">
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="completed_task" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>